smp_cms/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, jsonify
from flask_login import login_required
from smp_cms.user.models import User
from smp_cms.utils.view_utils import get_user_by_id

blueprint = Blueprint('user', __name__, static_folder='../static')


@blueprint.route('/users/<id>')
@login_required
@get_user_by_id
def get(user):
    return render_template('users/user_info.html', user_data=user.as_dict())

smp_cms/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Не прав доступа{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>У вас нет прав доступа к этой странице</a>
        </p>
    </div>
</div>
{% endblock %}

smp_cms/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Nikita N. Rams</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:reanimatolog@bk.ru">Contact</a></li>
    </ul>
  </small>
</footer>

smp_cms/templates/layout.html
{% import 'macros.html' as macros %}
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">

    <title>
        {% block page_title %}
            {% if page_title %}
                {{ page_title }}
            {% else %}
                SMP-CMS
            {% endif %}
        {% endblock %}
    </title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="author" content="{% block meta_author %}{% endblock %}">

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">

    {{ stylesheet_tag('main_css') | safe }}

    {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
    {% with form=form %}
        {% include "nav.html" %}
    {% endwith %}

    <header>{% block header %}{% endblock %}</header>

    <main role="main">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="row">
                    <div class="col-md-12">
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
                                {{ message }}
                            </div><!-- end .alert -->
                        {% endfor %}
                    </div><!-- end col-md -->
                </div><!-- end row -->
            {% endif %}
        {% endwith %}


            <div class="container-fluid">
                <div class="row">
                    {% if current_user and current_user.is_authenticated %}
                        <div class="col-2">{% block left_menu %}{{ macros.render_left_menu(curr_user, menus) }}{% endblock %}</div>
                        <div class="col-10">
                    {% else %}
                        <div class="col-12">
                    {% endif %}
                    {% block content %}{% endblock %}
                    </div>
                </div>
            </div>


        {% call() macros.render_modal("service-choice", "Выбор сервиса", "modal-lg service-choice-modal", "", "") %}
            <div class="container-fluid">
                <div class="row">
                    <div class="col">
                        {{ macros.render_button ( url_for('services.dashboard_common'), "Сводка", "") }}
                    </div>
                    <div class="col">
                        {{ macros.render_button ( url_for('services.dashboard_common'), "Архив", "") }}
                    </div>
                    <div class="col">
                        {{ macros.render_button ( url_for('services.dashboard_common'), "Пациенты", "") }}
                    </div>
                    <div class="col">
                        {{ macros.render_button ( url_for('services.dashboard_common'), "Статистика", "") }}
                    </div>
                    <div class="col">
                        {{ macros.render_button ( url_for('services.dashboard_common'), "Оперативная обстановка", "") }}
                    </div>
                </div>
            </div>
        {% endcall %}
    </main>


    {% include "footer.html" %}

    <!-- JavaScript at the bottom for fast page loading -->
    {{ javascript_tag('main_js') | safe }}
    {% block js %}{% endblock %}
    <!-- end scripts -->
{% endblock %}
</body>
</html>

smp_cms/templates/macros.html
{% macro render_modal (modal_id, header, class, submit_form_id = '', submit_button_caption='') %}
    <div id="{{ modal_id }}" class="modal fade " role="dialog">
        <div class="modal-dialog {{ class }}">
            <div class="modal-content">
                <div class="modal-header">
                    <a type="button" class="modal-icon" data-dismiss="modal"><i class="modal-icon-close"></i></a>
                    <div class="modal-title">{{ header }}</div>
                </div>
                <div class="modal-body">
                    {{ caller()|safe }}
                </div>
                <div class="modal-footer">
                    {% if submit_form_id %}
                        <a type="button" class="modal-button action-button-positive"
                           data-submit-form="{{ submit_form_id }}">
                            {% if submit_button_caption %}
                                {{ submit_button_caption }}
                            {% else %}
                                {{ "Save" }}
                            {% endif %}
                        </a>
                        <a type="button" class="modal-button action-button-neutral"
                           data-dismiss="modal">{{ "Cancel" }}</a>
                    {% else %}
                        <a type="button" class="modal-button action-button-neutral"
                           data-dismiss="modal">{{ "Close" }}</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endmacro %}

{% macro render_modal_trigger_button (modal_id, header, class) %}
    <button type="button" class="btn btn-primary {{ class }}" data-toggle="modal" data-target="#{{ modal_id }}">
        {{ header }}
    </button>
{% endmacro %}

{% macro render_button (url, header, class) %}
    <a href="{{ url }}" class="btn btn-primary btn-lg {{ class }}" role="button" aria-pressed="true">{{ header }}</a>
{% endmacro %}


{% macro render_simple_table (headers, items, class="", title="") %}
    <h3>{{ title }}</h3>
    <table class="table table-sm {{ class }}">
        <thead>
        <tr>
            {% for header in headers %}
                <th scope="col">{{ header }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for item in items %}
            <tr>
                {% for td_info in item %}
                    <td>{{ td_info }}</td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endmacro %}

{% macro render_left_menu (curr_user, menus) %}

    <div class="list-group">
        {% for item in menus %}
            {% if curr_user.role.type in item.roles %}
                <a href="{{ url_for( item.url ) }}" class="list-group-item list-group-item-action">
                    {{ item.title }}
                </a>
            {% endif %}
        {% endfor %}
    </div>
{% endmacro %}

smp_cms/templates/nav.html
{% import 'macros.html' as macros %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <span class="navbar-brand">
     {{ macros.render_modal_trigger_button ("service-choice", "Выбор сервиса", "d") }}
  </span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('public.home') }}">Старт
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.about') }}">О системе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.users') }}">Все пользователи</a>
      </li>
    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="navbar-nav my-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('user.get', id=current_user.id) }}">{{ current_user.name }} [{{ current_user.role.name }}]</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.logout') }}">
          <i class="fa fa-sign-out"></i>
        </a>
      </li>
    </ul>
    {% elif login_form %}
    <form class="form-inline" autocomplete="off" id="loginForm" method="POST" action="/" role="login">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <div class="input-group mb-2 mr-sm-2">
        {{ login_form.tab_id(placeholder="Табельный номер", class_="form-control mr-sm-1 my-auto") }} {{ login_form.password(placeholder="Password",
        class_="form-control mr-sm-1 my-auto") }}
        <button class="btn btn-light btn-primary m-auto" type="submit">Login</button>
      </div>
    </form>
    <ul class="navbar-nav my-auto">
      <li class="nav-item">

      </li>
    </ul>
    {% endif %}
  </div><!-- /.navbar-collapse -->
</nav>